project: 
  title: BenchmarkDotNET 科學化 .NET 應用效能調校
  render: 
    - slides/index.qmd

# picture url prefix
bdn_1_prefix: ./01_BDN_tutorial/
bdn_2_prefix: ./02_CSharp_BDN_examples/
bdn_3_prefix: ./03_GitHub_Action_CI/
perfview_intro_prefix: ./PerfView_Intro/